name: CI

{% if REPO|fnmatch('docker-mf*-*-buildimage') %}
    {% set LIST = REPO.split("-") %}
    {% set MODULE = LIST[1] %}
    {% set OS = LIST[2] %}
{% else %}
    {% set MODULE = "" %}
    {% set OS = "" %}
{% endif %}

on:
  push:
    branches: 
      - master
      - integration
      - experimental*
      - release_*
  repository_dispatch:
    types:
      - metwork-trigger*

env:
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: {% raw %}${{ github.event.client_payload.branch}}{% endraw %}

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: {% raw %}${{ github.event.client_payload.branch || github.ref }}{% endraw %}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: {% raw %}${{ secrets.DOCKER_USERNAME }}{% endraw %}
          password: {% raw %}${{ secrets.DOCKER_PASSWORD }}{% endraw %}
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            {% raw %}${{ steps.SetVariables.outputs.tag_branch }}{% endraw %}
            {% raw %}${{ steps.SetVariables.outputs.tag_latest }}{% endraw %}
          build-args: |
            BRANCH={% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
            CACHEBUST={% raw %}${{ github.run_number }}{% endraw %}
      - name: Image digest
        run: echo {% raw %}${{ steps.docker_build.outputs.digest }}{% endraw %}

