name: CI

on:
  push:
    branches: 
      - master
      - integration
      - experimental*
      - release_*
  repository_dispatch:
    types:
      - metwork-trigger*

env:
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: {% raw %}${{ github.event.client_payload.branch}}{% endraw %}
    PAYLOAD_OS: {% raw %}${{ github.event.client_payload.os}}{% endraw %}

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: {% raw %}${{ github.event.client_payload.branch || github.ref }}{% endraw %}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: debug env
        run: |
          env
          echo "Dockerfile"
          cat ./Dockerfile
      - name: docker build and push
        id: DockerStep
        env: 
          BRANCH: {% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          CACHEBUST: {% raw %}${{ github.run_number }}{% endraw %}
          TAG_BRANCH: {% raw %}${{ steps.SetVariables.outputs.tag_branch }}{% endraw %}
          TAG_LATEST: {% raw %}${{ steps.SetVariables.outputs.tag_latest }}{% endraw %}
        run: |
          echo {% raw %}${{ secrets.DOCKER_PASSWORD }}{% endraw %} | docker login -u {% raw %}${{ secrets.DOCKER_USERNAME }}{% endraw %} --password-stdin
          ${WORKFLOW_SCRIPTS_DIR}/docker_build.sh

{% if REPO == "docker-mfext-centos6-buildimage" %}
      - name: dispatch mfext
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfext
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
{% endif %}
{% if REPO == "docker-mfext-centos8-buildimage" %}
      - name: dispatch mfext
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfext
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
{% endif %}
{% if REPO == "docker-mfxxx-centos6-buildimage" %}
      - name: dispatch mfserv
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfserv
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfdata
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfdata
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfbase
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfbase
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfadmin
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfadmin
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfsysmon
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfsysmon
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfextaddon_python2
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_python2
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfextaddon_rabbitmq
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_rabbitmq
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
      - name: dispatch mfextaddon_elasticsearch
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.SetVariables.outputs.branch != 'release_1.1' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos6' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_elasticsearch
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos6"}'
{% endif %}
{% if REPO == "docker-mfxxx-centos8-buildimage" %}
      - name: dispatch mfserv
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false'  && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfserv
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfdata
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfdata
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfbase
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfbase
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfadmin
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfadmin
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfsysmon
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfsysmon
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfextaddon_python2
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_python2
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
      - name: dispatch mfextaddon_rabbitmq
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_rabbitmq
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}", "os": "centos8"}'
{% endif %}
