name: CI

on:
  push:
    branches: 
      - master
      - integration
      - experimental*
      - release_*
      - ci*
      - pci* 
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types:
      - metwork-trigger*

env:
    OS_VERSION: centos6
{% if "github-selfhosted" in "TOPICS"|getenv|from_json %}
{% if REPO == "mfextaddon_soprano" %}
    DOCKER_RUN_OPTIONS: "-v {% raw %}${{ github.workspace }}{% endraw %}:/src -v /buildcache:/buildcache -v /private:/private -e GITHUB_REF -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e GITHUB_REPOSITORY -e OS_VERSION"
{% else %}
    DOCKER_RUN_OPTIONS: "-v {% raw %}${{ github.workspace }}{% endraw %}:/src -v /buildcache:/buildcache -e GITHUB_REF -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e GITHUB_REPOSITORY -e OS_VERSION"
{% endif %}
{% endif %}
{% if "github-actions" in "TOPICS"|getenv|from_json %}
    DOCKER_RUN_OPTIONS: "-v {% raw %}${{ github.workspace }}{% endraw %}:/src -e GITHUB_REF -e GITHUB_RUN_NUMBER -e GITHUB_SHA -e GITHUB_REPOSITORY -e OS_VERSION"
{% endif %}
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: {% raw %}${{ github.event.client_payload.branch}}{% endraw %}

jobs:
  ci_build:
{% if "github-selfhosted" in "TOPICS"|getenv|from_json %}
    runs-on: [self-hosted, metwork]
{% endif %}
{% if "github-actions" in "TOPICS"|getenv|from_json %}
    runs-on: ubuntu-latest
{% endif %}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: {% raw %}${{ github.event.client_payload.branch || github.ref }}{% endraw %}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: debug env
        run: |
          env
      - name: bootstrap
        if: {% raw %}${{ steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        run: |
          TARGET_DIR={% raw %}${{ steps.SetVariables.outputs.target_dir }}{% endraw %}
          BRANCH={% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          TAG={% raw %}${{ steps.SetVariables.outputs.tag }}{% endraw %}
          DEP_DIR={% raw %}${{ steps.SetVariables.outputs.dep_dir }}{% endraw %}
          BUILDIMAGE={% raw %}${{ steps.SetVariables.outputs.buildimage }}{% endraw %}
          docker run ${DOCKER_RUN_OPTIONS} -e TARGET_DIR=${TARGET_DIR} -e BRANCH=${BRANCH} -e TAG=${TAG} -e DEP_DIR=${DEP_DIR} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/bootstrap_ci.sh"
      - name: build
        if: {% raw %}${{ steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        id: BuildStep
        run: |
          TARGET_DIR={% raw %}${{ steps.SetVariables.outputs.target_dir }}{% endraw %}
          BRANCH={% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          TAG={% raw %}${{ steps.SetVariables.outputs.tag }}{% endraw %}
          DEP_BRANCH={% raw %}${{ steps.SetVariables.outputs.dep_branch }}{% endraw %}
          BUILDIMAGE={% raw %}${{ steps.SetVariables.outputs.buildimage }}{% endraw %}
          docker run ${DOCKER_RUN_OPTIONS} -e TARGET_DIR=${TARGET_DIR} -e BRANCH=${BRANCH} -e DEP_BRANCH=${DEP_BRANCH} -e TAG=${TAG} --rm ${BUILDIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/build.sh"
      - name: publish buildlogs
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        uses: thebaptiste/ssh-scp-ssh-pipelines@metwork
        env:
          REMOTE: {% raw %}${{ steps.SetVariables.outputs.buildlog_dir }}{% endraw %}
          LOCAL: {% raw %}${{ github.workspace }}/buildlogs{% endraw %}
        with:
          host: {% raw %}${{ secrets.METWORKPUB_HOST }}{% endraw %}
          user: {% raw %}${{ secrets.METWORKPUB_USERNAME }}{% endraw %}
          pass: {% raw %}${{ secrets.METWORKPUB_PASSWORD }}{% endraw %}
          port: 22
          first_ssh: |
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/*' => ${REMOTE}
      - name: integration tests
        if: {% raw %}${{ steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        run: |
          TESTIMAGE={% raw %}${{ steps.SetVariables.outputs.testimage }}{% endraw %}
          DEP_BRANCH={% raw %}${{ steps.SetVariables.outputs.dep_branch }}{% endraw %}
          BRANCH={% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          docker run ${DOCKER_RUN_OPTIONS} -e DEP_BRANCH=${DEP_BRANCH} -e BRANCH=${BRANCH} --rm ${TESTIMAGE} /bin/bash -c "${DOCKER_WORKFLOW_SCRIPTS_DIR}/integration_tests.sh"
      - name: publish rpms
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.BuildStep.outputs.bypass == 'false' && steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        uses: thebaptiste/ssh-scp-ssh-pipelines@metwork
        env:
          REMOTE: {% raw %}${{ steps.SetVariables.outputs.rpm_dir }}{% endraw %}
          LOCAL: {% raw %}${{ github.workspace }}{% endraw %}/rpms
        with:
          host: {% raw %}${{ secrets.METWORKPUB_HOST }}{% endraw %}
          user: {% raw %}${{ secrets.METWORKPUB_USERNAME }}{% endraw %}
          pass: {% raw %}${{ secrets.METWORKPUB_PASSWORD }}{% endraw %}
          port: 22
          first_ssh: |
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/metwork-*.rpm' => ${REMOTE}
      - name: createrepo
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.BuildStep.outputs.bypass == 'false' && steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        uses: thebaptiste/ssh-scp-ssh-pipelines@metwork
        env:
          REMOTE: {% raw %}${{ steps.SetVariables.outputs.rpm_dir }}{% endraw %}
          LOCAL: {% raw %}${{ github.workspace }}{% endraw %}/.github/workflows
        with:
          host: {% raw %}${{ secrets.METWORKPUB_HOST }}{% endraw %}
          user: {% raw %}${{ secrets.METWORKPUB_USERNAME }}{% endraw %}
          pass: {% raw %}${{ secrets.METWORKPUB_PASSWORD }}{% endraw %}
          port: 22
          scp: |
            '${LOCAL}/createrepo.sh' => ${REMOTE}
          last_ssh: |
            cd ${REMOTE}
            chmod +x createrepo.sh
            ./createrepo.sh .
      - name: mageia_repo
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.BuildStep.outputs.bypass == 'false' && steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        uses: appleboy/ssh-action@master
        with:
          host: {% raw %}${{ secrets.METWORKPUB_HOST }}{% endraw %}
          username: {% raw %}${{ secrets.METWORKPUB_USERNAME }}{% endraw %}
          password: {% raw %}${{ secrets.METWORKPUB_PASSWORD }}{% endraw %}
          port: 22
          script: |
{% if "private-addon" in "TOPICS"|getenv|from_json %}
            docker run -v /private:/private --rm mageia:6 /bin/bash -c "genhdlist2 --allow-empty-media {% raw %}${{ steps.SetVariables.outputs.rpm_dir }}{% endraw %}"
{% else %}
            docker run -v /pub:/pub --rm mageia:6 /bin/bash -c "genhdlist2 --allow-empty-media {% raw %}${{ steps.SetVariables.outputs.rpm_dir }}{% endraw %}"
{% endif %}

      - name: publish doc
        if: {% raw %}${{ github.event_name != 'pull_request' && steps.BuildStep.outputs.bypass == 'false' && steps.SetVariables.outputs.branch != 'null' }}{% endraw %}
        uses: thebaptiste/ssh-scp-ssh-pipelines@metwork
        env:
          REMOTE: {% raw %}${{ steps.SetVariables.outputs.doc_dir }}{% endraw %}
          LOCAL: {% raw %}${{ github.workspace }}{% endraw %}/html_doc
        with:
          host: {% raw %}${{ secrets.METWORKPUB_HOST }}{% endraw %}
          user: {% raw %}${{ secrets.METWORKPUB_USERNAME }}{% endraw %}
          pass: {% raw %}${{ secrets.METWORKPUB_PASSWORD }}{% endraw %}
          port: 22
          first_ssh: |
            rm -rf ${REMOTE}
            mkdir -p ${REMOTE}
          scp: |
            '${LOCAL}/*' => ${REMOTE}
{% if "github-selfhosted" in "TOPICS"|getenv|from_json %}
      - name: clean cache on failure
        if: failure()
        run: |
          sudo rm -f {% raw %}${{ steps.BuildStep.outputs.buildcache }}{% endraw %}
{% endif %}
{% if REPO == "mfserv" or REPO == "mfdata" or REPO == "mfbase" %}
      - name: dispatch plugins buildimage centos7
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-{{REPO}}plugins-centos7-buildimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch plugins buildimage centos8
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-{{REPO}}plugins-centos8-buildimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% if REPO != "mfbase" %}
      - name: dispatch python2 tests
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/{{REPO}}_python2_tests
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% endif %}
{% if REPO == "mfext" %}
      - name: dispatch mfxxx testimage centos6
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-mfxxx-centos6-testimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfxxx testimage centos7
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-mfxxx-centos7-testimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfxxx buildimage centos6
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-mfxxx-centos6-buildimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfxxx buildimage centos7
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-mfxxx-centos7-buildimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfxxx buildimage centos8
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/docker-mfxxx-centos8-buildimage
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% if REPO == "mfextaddon_python2" %}
      - name: dispatch mfdata python2 tests
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfdata_python2_tests
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfserv python2 tests
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfserv_python2_tests
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfextaddon_mapserver
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_mapserver
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfextaddon_vim
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_vim
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
      - name: dispatch mfextaddon_scientific
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_scientific
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% if REPO == "mfextaddon_rabbitmq" %}
      - name: dispatch mfbus
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfbus
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% if REPO == "mfextaddon_scientific" %}
      - name: dispatch mfextaddon_radartools
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_radartools
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% if REPO == "mfextaddon_radartools" %}
      - name: dispatch mfextaddon_soprano
        if: {% raw %}${{ github.event_name != 'pull_request' && github.event_name != 'tags' && steps.SetVariables.outputs.branch != 'null' && steps.BuildStep.outputs.bypass == 'false' }}{% endraw %}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: {% raw %}${{ secrets.METWORK_ACCESS_TOKEN }}{% endraw %}
          repository: metwork-framework/mfextaddon_soprano
          event-type: metwork-trigger-{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}
          client-payload: '{"branch": "{% raw %}${{ steps.SetVariables.outputs.branch }}{% endraw %}"}'
{% endif %}
{% if "github-selfhosted" in "TOPICS"|getenv|from_json %}
      - name: chown on build outputs
        if: always()
        run: |
          sudo chown -R githubactions:metworkpub .
          sudo chmod -R 775 .
{% endif %}
