name: apply
on:
  push:
    paths:
      - 'common_files/**'
      - '.github/workflows/apply_common_files.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip git python3-setuptools-git python3-setuptools
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install git+https://github.com/metwork-framework/cookiecutter_hooks.git
          sudo pip3 install PyGithub
      - name: "apply"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
        run: |
          git config --global credential.helper cache
          cd /tmp
          ${GITHUB_WORKSPACE}/bin/get_repos.py --topic=integration-level-5 metwork-framework >/tmp/repos
          cat /tmp/repos
          for REPO in $(cat /tmp/repos); do git clone https://${{ secrets.CLONE_USERNAME }}:${{ secrets.CLONE_PASSWORD }}@github.com/metwork-framework/${REPO}.git; rm -Rf /tmp/common ; renvtpl ${GITHUB_WORKSPACE}/common_files /tmp/common; cd /tmp/common; post_gen_project ; cp -Rf * /tmp/${REPO} ; cp -Rf .* /tmp/${REPO} ; cd /tmp/${REPO} ; git status; git diff; cd /tmp; done
