name: apply
on:
  push:
    paths:
      - 'common_files/**'
      - '.github/workflows/apply_common_files.yml'
      - '.github/workflows/apply_common_files.sh'
      - 'bin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip git python3-setuptools-git python3-setuptools
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install git+https://github.com/metwork-framework/cookiecutter_hooks.git
          sudo pip3 install PyGithub
      - name: "apply"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
          USERNAME: ${{ secrets.CLONE_USERNAME }}
          PASSWORD: ${{ secrets.CLONE_PASSWORD }}
        run: |
          .github/workflows/apply_common_files.sh
