name: apply_config
on:
  push:
    paths:
      - .github/workflows/apply_config.yml
      - labels.json
      - releases.json
      - Makefile
      - bin/get_repos.py
  pull_request:
    paths:
      - .github/workflows/apply_config.yml
      - labels.json
      - releases.json
      - Makefile
      - bin/get_repos.py
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install yajl-tools python3 python3-pip git python3-setuptools-git python3-setuptools
      - name: "set up python deps"
        run: |
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install PyGithub
      - name: "validate"
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
          LIMIT_TO_REPO: ${{ github.event.inputs.limit_to_repo }}
        run: |
          make validate
      - name: "apply_config1"
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
        run: |
          make apply_config
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      - name: "apply_config2"
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
        run: |
          make apply_config
        if: github.ref == 'refs/heads/master' && github.event_name == 'schedule'
