name: apply
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: "test"
        run: |
          git config --global credential.helper cache
          git clone https://${{ secrets.CLONE_USERNAME }}:${{ secrets.CLONE_PASSWORD }}@github.com/metwork-framework/testrepo2
          cd testrepo2
          git checkout -b foo
          git push -u origin foo
