name: apply
on:
  push:
    paths:
      - 'common_files/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip git python3-setuptools-git python3-setuptools
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install PyGithub
      - name: "apply"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
        run: |
          git config --global credential.helper cache
          cd /tmp
          ${GITHUB_WORKSPACE}/bin/get_repos.py --topic=integration-level-5 metwork-framework >/tmp/repos
          for REPO in $(cat /tmp/repos); do git clone https://${{ secrets.CLONE_USERNAME }}:${{ secrets.CLONE_PASSWORD }}@github.com/metwork-framework/${REPO}; renvtpl ${GITHUB_WORKSPACE}/common_files /tmp/${REPO}; cd /tmp/${REPO}; git status; git diff; done
