name: copy_branch
on:
  workflow_dispatch:
   inputs:
     limit_to_repo:
       descript: "if set limit to this repo"
       default: ''
       required: false
     source_branch:
       descript: "source branch"
       default: 'integration'
       required: true
     target_branch:
       descript: "target branch"
       default: 'master'
       required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install yajl-tools python3 python3-pip git python3-setuptools-git python3-setuptools
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install git+https://github.com/metwork-framework/cookiecutter_hooks.git
          sudo pip3 install PyGithub
      - name: "validate"
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
          LIMIT_TO_REPO: ${{ github.event.inputs.limit_to_repo }}
        run: |
          make validate
      - name: "apply"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
          USERNAME: ${{ secrets.CLONE_USERNAME }}
          PASSWORD: ${{ secrets.CLONE_PASSWORD }}
          LIMIT_TO_REPO: ${{ github.event.inputs.limit_to_repo }}
          SOURCE_BRANCH: ${{ github.event.inputs.source_branch }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          bin/copy_branch.sh
