name: apply_common_files
on:
  workflow_dispatch:
   inputs:
     limit_to_repo:
       descript: "if set limit to this repo"
       default: ''
       required: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: "set up system deps"
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip git python3-setuptools-git python3-setuptools
          sudo pip3 install git+https://github.com/metwork-framework/envtpl.git
          sudo pip3 install git+https://github.com/metwork-framework/cookiecutter_hooks.git
          sudo pip3 install PyGithub
      - name: "apply"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOK }}
          USERNAME: ${{ secrets.CLONE_USERNAME }}
          PASSWORD: ${{ secrets.CLONE_PASSWORD }}
          LIMIT_TO_REPO: ${{ github.event.inputs.limit_to_repo }}
        run: |
          .github/workflows/copy_integration_master.sh
